### ISSUE TITLE
Updates for our mod

### ISSUE THREAD

**Issue by YisusCL1** [draxios/bizzymod#19]
1- Tank HP is 3000 and it should be 2000
2- There should be 2 M2's before M2 cooldown (i forgot to tell You this)
3- The Spawn timer should be 2 seconds instead of immediate Spawn (i forgot to tell You this as well, sorry)
4- The player should have 2 tank controls instead of only 1
5- When the player loses both tank controls the tank should automatically die instead of being AI
6- When tank spawns, survivor points should freeze
7- Cut melees should spawn as well
8- Killing the witch should give 10 bonus points to the survivor
9- There should be 2 M2's before M2 cooldown
10- When the player deadstops the hunter, there should be a text that says like "-YisusCL deadstopped scream"
11- At the end of every round, there should be a round fact that says how many hunters were skeeted and how many deadstops were given to the hunters
12- If it's possible, can there be a round fact that says how many hunters were melee skeeted as well?
13- Idk if it's because of our Bad timing+aim but we couldnt melee skeet each other but like when the hunter goes straight to the Survivor like face to face
14- The deadstop frame to the hunter should be more accurate, like, so it's harder to deadstop the hunter.
15-  Can you change the mod's name to "Deadman1v1"?

**Comment by draxios** [comment]
closing for next testing as since we have two issues open for same thing.
