### ISSUE TITLE
deadman mod

### ISSUE THREAD

**Issue by YisusCL1** [draxios/bizzymod#21]
none of the commands and texts are working (i.e !tank !mvp, etc, neither the text that says (-YisusCL skeeted scream in "x" shots YisusCL deadstopped scream, YisusCL skeeted a rock, triggered alarm,etc)
when the hunter pounces the survivor, the survivor instantly dies instead of just taking 25 hp away
the tank dies after 1 control instead of 2
witch can't be draw crowned
still can't melee skeet a hunter when the hunter comes face to face

**Comment by draxios** [comment]
closing as completed, testing will prolly allow more later.
