### ISSUE TITLE
Kneemod Update/Change Request

### ISSUE THREAD

**Issue by Knee89** [draxios/bizzymod#32]
Here's a list of some idea's/change requests to Kneemod!
Thanks Bizzy!

Survivors:
+ Decrease total # of available M2's before triggering recharge by 50%
+ Enable crawling/moving while incapped
+ Health Kits at chapter start (provide temp health bonus only) <----In addition to the adrenaline
+ Bleed-Out rate increase by 250%
+ Incapped survivors deal FF, able to shoot gas cans
+ Limit Pistol ammo
+ Increase general FF damage by 10%

Infected:
+ Reset SI Health totals to 80% of standard, including Tank
+ CI Health set to 50% of standard
+ Special Infected M2's do +100% damage of standard
+ Spawn timers set to min 20 sec
+ Total number of spawning Common-Infected reset to 75% of standard.
+ Prevent a Jockey or Hunter deadstop after there would be 5 pts of fall damage.
+ Increase Boomer and Smoker visual disturbance effect duration +50%
+ Increase Tank Speed by 15% (faster than Survivors, kinda like Witch, will make Tank WAY scarier)
+ Increase Tank rocks' HP by 300%
+ Booming/Spitting on a lit Tank puts it out, as well as Bile Jars thrown at a lit Tank. **<---idk if possible but always wanted this**

Let me know if ya need any help or clarification!

Thanks again,

Knee

**Comment by draxios** [comment]
Survivors:

- [✓] Decrease total # of available M2's before triggering recharge by 50%

- [✓] Enable crawling/moving while incapped

- [✓] Health Kits at chapter start (provide temp health bonus only) <----In addition to the adrenaline

- [✓] Bleed-Out rate increase by 250%

- [✘] Incapped survivors deal FF, able to shoot gas cans

- [✘ ] Limit Pistol ammo

- [✓] Increase general FF damage by 10%

Infected:

- [✓] Reset SI Health totals to 80% of standard, including Tank

- [✓] CI Health set to 50% of standard

- [✓] Special Infected M2's do +100% damage of standard

- [✘] Spawn timers set to min 20 sec

- [✓] Total number of spawning Common-Infected reset to 75% of standard.

- [✘] Prevent a Jockey or Hunter deadstop after there would be 5 pts of fall damage.

- [✓] Increase Boomer and Smoker visual disturbance effect duration +50%

- [✓] Increase Tank Speed by 15% (faster than Survivors, kinda like Witch, will make Tank WAY scarier)

- [✘] Increase Tank rocks' HP by 300%

- [✘] Booming/Spitting on a lit Tank puts it out, as well as Bile Jars thrown at a lit Tank. <---idk if possible but always wanted this
