### ISSUE TITLE
Final issues for Deadman1v1

### ISSUE THREAD

**Issue by yungscream** [draxios/bizzymod#34]
-add standed witches to meleecrown (add 20 bonus when you make a meleecrown, if its not possible just add standed witches)
-add 2 frustr control barz to the tank
-try to make the meleeskeet more easier (if its not possible dont do it thx)
-add 25 extra damage when a hunter make a 25 pounce
-add 3 M2's but the m2 cooldown should start on the 3rd M2
-add a chat when someone m2's the hunter like "scream deadstopped -YisusCL" and also when the witch gets crowned like "scream crowned the Witch" "scream dragcrowned the Witch" scream meleecrowned the Witch" (if its not possible dont do it)

**Comment by draxios** [comment]
yungscream raged, so closing this.
