### ISSUE TITLE
Bananamod updates :D

### ISSUE THREAD

**Issue by ThenieBeanie** [draxios/bizzymod#37]
Hey bizzy bee, here are some of the things that Moon and I have been talking about. No rush on anything and I don't want to add something to your plate if you are too "bizzy." Haha, you get it? Sorry, I'll stop...

So the main thing for me is that I would like for the servers to represent the newest updates to the Zonemod maps, I think they are on 2.6 or something now so I was hoping it could be possible to just upload those same maps with this mod?

I don't know how many pills I set to spawn but just to quantify it so I can know, 4 pill spawns would be a good balance I think.

Out of spite I had it set so that no pumps spawned but apparently some people actually like the pump, which I think is gross but I'm here for the people y'know, so I think a change to 60% Chrome shotgun spawns and 40% pumps would be good. 

2 magnum limit.

We should probably remove quads because I don't think anybody would know how to deal with them.

That's all I can think of for now, sorry I wrote a lot, I'm not sure why I thought you would need any of the reasons behind why I did anything but I felt if I just listed stuff it would sound so demanding and you are doing me a favor so I wanted to be friendly hehe.

Thanks again!!

Very respectfully, 

ThenieBeanie :)

**Comment by draxios** [comment]
I was expecting a short story, but alas this was a great read nonetheless. Bananamod ist updated!
